###DynamicEconomy配置文件###
#powered by smyhw 
#OurWorld Community
#动态经济

config:
  #插件提示消息的前缀
  prefix: "[DynamicEconomy]"
 #每次降价降多少？
#只要你的货币系统支持，这个值最大精确到小数点后15位
  cuts: 0.001
 #每次降价后给其他物品涨价多少?
#只要你的货币系统支持，这个值最大精确到小数点后15位
  increase: 0.0001
 #给予玩家货币的指令
#%num%将被替换成货币的数量
#%player%将被替换成玩家ID
  cmd: eco give %player% %num% 